Vagrant.configure("2") do |config|

  config.vm.define "gamepetto-wildfly" do |v|
    v.vm.box = "ubuntu/xenial64"
    v.vm.network "forwarded_port", guest: 8090, host: 8090
    v.vm.network "forwarded_port", guest: 8080, host: 8080
    v.vm.network "forwarded_port", guest: 9990, host: 9990
    v.vm.network "forwarded_port", guest: 9993, host: 9993
    v.vm.provision :shell, :path => "install-wildfly.sh"

    v.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
  end

  config.vm.define "gamepetto-mysql" do |v|
    v.vm.box = "ubuntu/xenial64"
    v.vm.network "forwarded_port", guest: 3306, host: 3306
    v.vm.provision :shell, :path => "install-mysql.sh"

    v.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
  end

end
