server:
  port: 8090
  servlet:
    context-path: "/api"

spring:
  profiles:
    active: ${GAMEPETTO_SPRING_PROFILE}
  application:
    name: GamepettoBackend

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${GAMEPETTO_JDBC_URL}?serverTimezone=UTC
    username: ${GAMEPETTO_DB_USER}
    password: ${GAMEPETTO_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
